name: athkar_app
description: "تطبيق أذكار إسلامية مع مواقيت الصلاة واتجاه القبلة"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- State Management ---
  provider: ^6.1.5
  get_it: ^8.0.3
  flutter_riverpod: ^2.4.9

  # --- Storage ---
  shared_preferences: ^2.2.2

  # --- Notifications ---
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

  # --- Firebase (آخر الإصدارات المتوافقة) ---
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_remote_config: ^5.1.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3

  # --- Location & Prayer ---
  adhan: ^2.0.0+1
  geolocator: ^10.1.1
  geocoding: ^4.0.0
  flutter_compass: ^0.8.0
  permission_handler: ^11.4.0

  # --- Date & Time ---
  intl: ^0.19.0        # مطلوب من Flutter SDK
  hijri: ^3.0.0
  flutter_timezone: ^4.1.1

  # --- Utilities ---
  share_plus: ^7.2.2
  battery_plus: ^6.2.1
  sensors_plus: ^6.1.1
  in_app_review: ^2.0.10
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
