name: athkar_app
description: "تطبيق أذكار إسلامية مع مواقيت الصلاة واتجاه القبلة"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI/Design
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  
  # State Management
  provider: ^6.1.5
  get_it: ^8.0.3
  flutter_riverpod: ^2.4.9
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4

  # Notifications
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  rxdart: ^0.28.0

  # Location & Prayer
  adhan: ^2.0.0+1
  geolocator: ^10.1.1
  geocoding: ^4.0.0
  flutter_compass: ^0.8.0
  permission_handler: ^11.4.0

  # Date/Time
  intl: ^0.19.0  # Required by Flutter SDK
  hijri: ^3.0.0
  flutter_timezone: ^4.1.1

  # Networking
  http: ^1.4.0
  
  # Utilities
  share_plus: ^7.2.2
  battery_plus: ^6.2.1
  device_info_plus: ^10.1.0  # Compatible version
  package_info_plus: ^8.3.0  # Compatible version
  app_settings: ^6.1.1
  flutter_native_timezone_latest: ^1.0.0
  loading_animation_widget: ^1.3.0
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.2.1
  equatable: ^2.0.7
  sensors_plus: ^6.1.1
  go_router: ^14.2.0  # Avoiding retracted version
  url_launcher: ^6.3.1
  in_app_review: ^2.0.10
  fl_chart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700